### ISSUE TITLE
Design of User interface

### ISSUE THREAD

**Issue by damniko** [mirakst/P3-Project#122]

**Comment by Mthage20** [comment]
Der er tilføjet et lille stykke om filter-knappen for log komponenten :) Er usikker på, hvor i processen vi er ift. at få den 100% implementeret i manager vinduet, men ellers er afsnittet færdigt.

**Comment by mirakst** [comment]
what the fuck der er comments

**Comment by AndersMariegaard** [comment]
What the frick der er sku da ikke nogen der læser hernede

**Comment by mirakst** [comment]
enig
