### ISSUE TITLE
Manager detached chart datagrid has more cells than it should (image in desc)

### ISSUE THREAD

**Issue by AndersMariegaard** [mirakst/P3-Project#181]
![image.png](https://app.gitkraken.com/api/glo/boards/61370a1579d3ee004b5dba07/attachments/61af732b86bf550047e38aeb)

This is most likely due to the few extra columns shown in the image underneath;
![image.png](https://app.gitkraken.com/api/glo/boards/61370a1579d3ee004b5dba07/attachments/61af766586bf550047e38bd7)

**Comment by damniko** [comment]
AutoGenerateColumns="False" i Xaml
